### ISSUE TITLE
In the GUI, if I try with a URI and then try again with a different URI, it does not update

### ISSUE THREAD

**Issue by shawnmjones** [mahanama94/memento-validator#3]
Steps to reproduce:
1. visit the validator at http://labs.mementoweb.org/validator/app/
2. click "Validate" with the default URI of https://dbpedia.org/page/Berlin, i.e., change nothing on the form
3. replace the URI with a memento, like http://web.archive.org/web/20010911203610/http://www.cnn.com/
4. change type to "Memento"
5. click "Validate" and nothing happens, the results still reflect the original dbpedia.org URI

**Comment by mahanama94** [comment]
Fixed, Issue was only with the front-end fixed in e6add392b4384cfe082ee56e638762daf0c2f67d

Not yet deployed.

**Comment by mahanama94** [comment]
Deployed. Please check. Thanks
