### ISSUE TITLE
TimeMap validation in the GUI fails with Internet Archive Memento

### ISSUE THREAD

**Issue by shawnmjones** [mahanama94/memento-validator#5]
Steps to reproduce:
1. copy a TimeMap URI-T from the Internet Archive - I used http://web.archive.org/web/timemap/link/http://www.cnn.com:80/
2. paste it into the URI field
3. change the Type to "TimeMap"
4. click Validate and nothing displays on the screen

In the developer tools under network, I see that a 502 is being returned from http://labs.mementoweb.org/validator/?datetime=Sun,+01+Apr+2010+12:00:00+GMT&uri=http:%2F%2Fweb.archive.org%2Fweb%2Ftimemap%2Flink%2Fhttp:%2F%2Fwww.cnn.com:80%2F&type=timemap&followLinks=true&fullTMCheck=false

I'm guessing that this 502 is not handled by the code in the page.

**Comment by mahanama94** [comment]
I tried to replicate the error locally and couldn't. I fixed missing error handling in the front-end in the latest commits and updated it on the server.

**Comment by shawnmjones** [comment]
Your other changes appear to have addressed this issue. Closing now.
