### ISSUE TITLE
Clicking "Memento Validator" in the GUI does not take the user "home"

### ISSUE THREAD

**Issue by shawnmjones** [mahanama94/memento-validator#6]
In many web apps, clicking the link in the upper left corner brings the user "Home", giving them a fresh version of the landing page for the application. This is often a way to reset the form to a default state.

The Memento Validator link just goes to #, which doesn't do anything unless there is JavaScript code that is waiting to respond to it. If that is the case, then the JavaScript code is not responding properly.

**Comment by mahanama94** [comment]
Fixed 159f2e3083755cf551a1ed7776637a52379ca742, I've missed it in the code.
